backend:
  name: git-gateway
  repo: brian-guerrero/augie-catholic

media_folder: static/assets
public_folder: assets

collections:
  - name: "event"
    label: "Events"
    folder: "src/pages/calendar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", default: "", format: "MMM Do YY"}
      - {label: "Location", name: "description", widget: "text"}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/about/history.md"
      label: "History"
      name: "history"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/about/chaplain.md"
      label: "Chaplain"
      name: "chaplain"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/prayer/index.md"
      label: "Prayer"
      name: "prayer"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/prayer/about-adoration.md"
      label: "About Adoration"
      name: "about-adoration"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/service/index.md"
      label: "Service"
      name: "service"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
