backend:
  name: git-gateway
  repo: brian-guerrero/augie-catholic

media_folder: static/assets
public_folder: assets

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/calendar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", default: "", format: "MMM Do YY"}
      - {label: "Location", name: "description", widget: "text"}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/about/index.md"
      label: "About"
      name: "about"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/services/index.md"
      label: "Services"
      name: "services"
      fields:
          - {label: "Template", name: "template", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
